---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ17N18"
  stages:
    Release:
      cfCredentialsId: "git-credentials"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    source: HelloWorldUI5
    npmExecuteLint: false
  Acceptance:
    cloudFoundryDeploy: false
    npmExecuteEndToEndTests: false
  Malware Scan:
    malwareExecuteScan: false
  Release:
    tmsExport: false
    tmsUpload: false
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "266a4be8trial"
    cfSpace: "MyFirstSpace"
    deployType: "standard"
    cloudFoundryDeploy: true
  Additional Unit Tests:
    npmExecuteScripts: false
  Compliance:
    sonarExecuteScan: false
steps:
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
